CREATE TABLE ALUNO
(
  RA INT IDENTITY(1,1),
  NOME VARCHAR(50)
  CONSTRAINT PK_ALUNO PRIMARY KEY (RA)
);

CREATE TABLE DISCIPLINA
(
  CODIGO INT IDENTITY(1,1),
  NOME VARCHAR(50),
  CARGA_HORARIA NUMERIC(10,2),
  CONSTRAINT PK_DISCIPLINA PRIMARY KEY (CODIGO)
);

CREATE TABLE MATRICULA
(
  ID_ALUNO INT,
  ID_DISCIPLINA INT,
  ANO INT NOT NULL,
  SEMESTRE INT NOT NULL,
  NOTA1 NUMERIC (10,2),
  NOTA2 NUMERIC (10,2),
  NOTASUB NUMERIC (10,2),
  MEDIA NUMERIC (10,2),
  FREQUENCIA NUMERIC(10,2),
  SITUACAO VARCHAR(20)
  CONSTRAINT FK_ALUNO_MATRICULA FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO(RA),
  CONSTRAINT FK_DISCIPLINA_MATRICULA FOREIGN KEY (ID_DISCIPLINA) REFERENCES DISCIPLINA(CODIGO),
  CONSTRAINT PK_ALUNO_DISCIPLINA PRIMARY KEY (ID_ALUNO, ID_DISCIPLINA)
);

DROP TABLE ALUNO;
DROP TABLE DISCIPLINA;
DROP TABLE MATRICULA;

INSERT INTO ALUNO
VALUES('GABRIEL');

INSERT INTO ALUNO
VALUES('FELIPE');

INSERT INTO ALUNO
VALUES('FABIO');

INSERT INTO ALUNO
VALUES('LETICIA');

INSERT INTO DISCIPLINA
VALUES('SO', 100);

INSERT INTO DISCIPLINA
VALUES('BANCO DE DADOS', 50);

INSERT INTO MATRICULA (ID_ALUNO, ID_DISCIPLINA, ANO, SEMESTRE, NOTA1, NOTA2, FREQUENCIA, SITUACAO)
VALUES(3,2,2025,1,8.0,8.0,75.00,'REPROVADO');

SELECT * FROM ALUNO;
SELECT * FROM DISCIPLINA;
SELECT * FROM MATRICULA;
DELETE FROM MATRICULA;