CREATE OR ALTER PROC 
CALCULO_MEDIA_FALTA
@ANO INT,
@SEMESTRE INT
AS
BEGIN
--DECLARANDO CURSOR PARA PERCORRER A TABELA
	DECLARE AUX_CURSOR CURSOR FOR
	SELECT ID_ALUNO,
		   ID_DISCIPLINA,
		   NOTA1,
		   NOTA2,
		   NOTASUB,
		   MEDIA,
		   FREQUENCIA
	FROM MATRICULA
	WHERE @ANO = ANO AND @SEMESTRE = SEMESTRE;

	OPEN AUX_CURSOR

	DECLARE
	@ID INT,
	@CODIGO INT,
	@NOTA1 NUMERIC(10,2),
	@NOTA2 NUMERIC(10,2),
	@MEDIA NUMERIC(10,2),
	@NOTASUB NUMERIC(10,2),
	@FREQUENCIA NUMERIC(10,2)
--AQUI O CURSOR ATRIBUI OS VALORES DAS VARIAVEIS DO PRIMEIRO REGISTRO
	FETCH NEXT FROM AUX_CURSOR
	INTO @ID, @CODIGO, @NOTA1, @NOTA2, @NOTASUB, @MEDIA, @FREQUENCIA

--ENQUANTO O LAÇO ACHAR REGISTRO, O LAÇO CONTINUARA
	WHILE @@FETCH_STATUS = 0
	BEGIN
--VERIFICO SE A NOTA É NULA, SE FOR EU ATRIBUO 0 E ATUALIZO NA TABELA
		IF(@NOTA1 IS NULL)
		BEGIN
			SET @NOTA1 = 0
			UPDATE MATRICULA
			SET NOTA1 = @NOTA1
			WHERE ID_ALUNO = @ID AND ID_DISCIPLINA = @CODIGO
		END
		IF(@NOTA2 IS NULL)
		BEGIN
			SET @NOTA2 = 0
			UPDATE MATRICULA
			SET NOTA2 = @NOTA2
			WHERE ID_ALUNO = @ID AND ID_DISCIPLINA = @CODIGO 
		END
--SE O USUARIO PASSAR ALGUMA NOTA SUB, EU VERIFICO E FAÇO AS SUBSTITUIÇÕES
		IF(@NOTASUB IS NOT NULL)
		BEGIN
			IF(@NOTA1 < @NOTA2)
			BEGIN
				SET @NOTA1 = @NOTASUB

				UPDATE MATRICULA
				SET NOTASUB = @NOTASUB
				WHERE ID_ALUNO = @ID AND ID_DISCIPLINA = @CODIGO


				SET @MEDIA = (@NOTA1 + @NOTA2) / 2

				UPDATE MATRICULA
				SET MEDIA = @MEDIA
				WHERE ID_ALUNO = @ID AND ID_DISCIPLINA = @CODIGO
			END
			IF(@NOTA1 > @NOTA2)
			BEGIN
				SET @NOTA2 = @NOTASUB

				UPDATE MATRICULA
				SET NOTASUB = @NOTASUB
				WHERE ID_ALUNO = @ID AND ID_DISCIPLINA = @CODIGO

				SET @MEDIA = (@NOTA1 + @NOTA2) / 2

				UPDATE MATRICULA
				SET MEDIA = @MEDIA
				WHERE ID_ALUNO = @ID AND ID_DISCIPLINA = @CODIGO
			END
		END
--CASO NAO, FAÇO A MEDIA NORMALMENTE
		ELSE
		BEGIN
			SET @MEDIA = (@NOTA1 + @NOTA2) / 2

			UPDATE MATRICULA
			SET MEDIA = @MEDIA
			WHERE ID_ALUNO = @ID AND ID_DISCIPLINA = @CODIGO
		END;

		IF(@MEDIA < 6)
		BEGIN
			UPDATE MATRICULA
			SET SITUACAO = 'REPROVADO POR NOTA'
			WHERE ID_ALUNO = @ID AND ID_DISCIPLINA = @CODIGO
		END
		ELSE
		BEGIN
			UPDATE MATRICULA
			SET SITUACAO = 'APROVADO'
			WHERE ID_ALUNO = @ID AND ID_DISCIPLINA = @CODIGO
		END

		IF(@FREQUENCIA < 75.00)
		BEGIN
			UPDATE MATRICULA
			SET SITUACAO = 'REPROVADO POR FALTA'
			WHERE ID_ALUNO = @ID AND ID_DISCIPLINA = @CODIGO
		END

		IF(@MEDIA < 6 AND @FREQUENCIA < 75.00)
		BEGIN
			UPDATE MATRICULA
			SET SITUACAO = 'REPROVADO POR FALTA'
			WHERE ID_ALUNO = @ID AND ID_DISCIPLINA = @CODIGO
		END

--DEPOIS QUE FAÇO AS VERIFICAÇÕES, JOGO AS INFORMAÇÕES PARA O PROXIMO REGISTRO, ATÉ O LAÇO ACABAR
		FETCH NEXT FROM AUX_CURSOR
		INTO @ID, @CODIGO, @NOTA1, @NOTA2, @NOTASUB, @MEDIA, @FREQUENCIA
		END;

		CLOSE AUX_CURSOR
		DEALLOCATE AUX_CURSOR
END;

EXEC CALCULO_MEDIA_FALTA 2025, 1